POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2M2U2MzY3ZDcyZWQyZjJjM2QzNzBiNmIiLCJpYXQiOjE2NzYwMzM0NTB9.3Tw_TMYxI_RaGMMjTOa1UjtMIfTE-PbOY5P2T18rkQE

{
    "title": "days after light",
    "author": "Ban Gibralt",
    "url": "https://www.google.com",
    "likes": 0,
    "userId": "63e6367d72ed2f2c3d370b6b"
}