PUT http://localhost:3003/api/blogs/63e4a9886cc
Content-Type: application/json

{
    "title": "päivitetty",
    "author": "rest pai",
    "url": "localhost:3001/api/blogs",
    "likes": 100,
    "id": "63e4a9886cc"
}